from fastapi import APIRouter
import json
import os

router = APIRouter()

DATA_PATH = "data/daily_data"

# Scraper name -> JSON file mapping
SCRAPER_MAP = {
    "topmbacollegedetails1_40": "topmbacollegedetails1_40.json",
    "topmbacollegedetails41_80": "topmbacollegedetails41_80.json",
    "topmbacollegedetails81_all":"topmbacollegedetails81_all.json",
    "allindiambacollegedetails1_40":"allindiambacollegedetails1_40.json",
    "allindiambacollegedetails41_100":"allindiambacollegedetails41_100.json",
    "allindiambacollegedetails101_140":"allindiambacollegedetails101_140.json",
    "allindiambacollegedetails141_180":"allindiambacollegedetails141_180.json",
    "allindiambacollegedetails181_220":"allindiambacollegedetails181_220.json",
    "allindiambacollegedetails221_260":"allindiambacollegedetails221_260.json",
    "allindiambacollegedetails261_300":"allindiambacollegedetails261_300.json",
    "allindiambacollegedetails301_340":"allindiambacollegedetails301_340.json",
    "allindiambacollegedetails341_370":"allindiambacollegedetails341_370.json",
    "allindiambacollegedetails371_380":"allindiambacollegedetails371_380.json",
    "allindiambacollegedetails381_420":"allindiambacollegedetails381_420.json",
    "distancemba":"distancemba.json",
    "executivemba":"executivemba.json",
    "mba":"mba.json",
    "parttimemba":"parttimemba.json",
    "mbageneralmanagement": "mbageneralmanagement.json",
    "mbainagriculture":"mbainagriculture.json",
    "mbaindataanalytics":"mbaindataanalytics.json",
    "mbaindatascience":"mbaindatascience.json",
    "mbaindigitalmarketing":"mbaindigitalmarketing.json",
    "mbainentrepreneurship":"mbainentrepreneurship.json",
    "onlinemba":"onlinemba.json",
    "atma":"atma.json",
    "cat":"cat.json",
    "cmat":"cmat.json",
    "engineeringcollegedetails1_40":"engineeringcollegedetails1_40.json",
    "engineeringcollegedetails41_80":"engineeringcollegedetails41_80.json",
    "engineeringcollegedetails81_120":"engineeringcollegedetails81_120.json",
    "engineeringcollegedetails121_160":"engineeringcollegedetails121_160.json",
    "ibsat":"ibsat.json",
    "kiitee":"kiitee.json",
    "mat":"mat.json",
    "mbainfamilybusiness":"mbainfamilybusiness.json",
    "mbainfinance":"mbainfinance.json",
    "mbainhealthcaremanagement":"mbainhealthcaremanagement.json",
    "mbainhrhumanresource":"mbainhrhumanresource.json",
    "mbaininternationalbusiness":"mbaininternationalbusiness.json",
    "mbainitsystems":"mbainitsystems.json",
    "mbainoperations":"mbainoperations.json",
    "mbainpharmaceuticalmanagement":"mbainpharmaceuticalmanagement.json",
    "mbainsalesmarketing":"mbainsalesmarketing.json",
    "nmat":"nmat.json",
    "productmanagement":"productmanagement.json",
    "snap":"snap.json",
    "upcat":"upcat.json",
    "xat":"xat.json",
    "aeronauticalengineering":"aeronauticalengineering.json",
    "aerospaceengineering":"aerospaceengineering.json",
    "aircraftmaintenanceengineering":"aircraftmaintenanceengineering.json",
    "automobileengineering":"automobileengineering.json",
    "bebtech":"bebtech.json",
    "biomedicalengineering":"biomedicalengineering.json",
    "biotechnologyengineering":"biotechnologyengineering.json",
    "bitsat":"bitsat.json",
    "ceramicengineering":"ceramicengineering.json",
    "cgcuet":"cgcuet.json",
    "chemicalengineering":"chemicalengineering",
    "civilengineering":"civilengineering.json",
    "comedkuget":"comedkuget.json",
    "communicationsengineering":"communicationsengineering.json",
    "computerscienceengineering":"computerscienceengineering.json",
    "constructionengineering":"constructionengineering.json",
    "controlsystems":"controlsystems.json",
    "cucetchandigarhuniversity":"cucetchandigarhuniversity.json",
    "dairytechnology":"dairytechnology.json",
    "diploma":"diploma.json",
    "distancebtech":"distancebtech.json",
    "distancediploma":"distancediploma.json",
    "electricalengineering":"electricalengineering.json",
    "electronicscommunicationengineering":"electronicscommunicationengineering.json",
    "electronicsengineering":"electronicsengineering.json",
    "environmentalengineering":"environmentalengineering.json",
    "foodtechnology":"foodtechnology.json",
    "gate":"gate.json",
    "geneticengineering":"geneticengineering.json",
    "industrialengineering":"industrialengineering.json",
    "informationtechnology":"informationtechnology.json",
    "jeeadvanced":"jeeadvanced.json",
    "jeemain":"jeemain.json",
    "jet":"jet.json",
    "jutefibertechnology":"jutefibertechnology.json",
    "lpunest":"lpunest.json",
    "marineengineering":"marineengineering.json",
    "materialsscience":"materialsscience.json",
    "mechanicalengineering":"mechanicalengineering.json",
    "mechatronicsengineering":"mechatronicsengineering.json",
    "memtech":"memtech.json",
    "metallurgicalengineering":"metallurgicalengineering.json",
    "microelectronics":"microelectronics.json",
    "miningengineering":"miningengineering.json",
    "nanotechnology":"nanotechnology.json",
    "navalarchitecture":"navalarchitecture.json",
    "petroleumengineering":"petroleumengineering.json",
    "phd":"phd.json",
    "powerengineering":"powerengineering.json",
    "productionengineering":"productionengineering.json",
    "pulppapertechnology":"pulppapertechnology.json",
    "rfmicrowaveengineering":"rfmicrowaveengineering.json",
    "roboticsengineering":"roboticsengineering.json",
    "structuralengineering":"structuralengineering",
    "telecommunicationengineering":"telecommunicationengineering.json",
    "textileengineering":"textileengineering.json",
    "toolengineering":"toolengineering.json",
    "transportationengineering":"transportationengineering.json",
    "vlsidesign":"vlsidesign.json",
    "wbjee":"wbjee.json",
    "aiapget":"aiapget.json",
    "alldentalcollegedetails":"alldentalcollegedetails.json",
    "allmedicalcollegedetails":"allmedicalcollegedetails.json",
    "alternativemedicine":"alternativemedicine.json",
    "appareldesign":"appareldesign.json",
    "automotivedesign":"automotivedesign.json",
    "bdes":"bdes.json",
    "bdesfashion":"bdesfashion.json",
    "bdesinterior":"bdesinterior.json",
    "bmlt":"bmlt.json",
    "bscfashion":"bscfashion.json",
    "bscininteriordesign":"bscininteriordesign.json",
    "ceramicglass":"ceramicglass.json",
    "clinicalpsychology":"clinicalpsychology.json",
    "clinicalresearch":"clinicalresearch.json",
    "communicationdesign":"communicationdesign.json",
    "dental":"dental.json",
    "dieteticsnutrition":"dieteticsnutrition.json",
    "exhibitiondesign":"exhibitiondesign.json",
    "fashiondesigning":"fashiondesigning.json",
    "filmvideodesign":"filmvideodesign.json",
    "fmge":"fmge.json",
    "footweardesign":"footweardesign.json",
    "furnituredesign":"furnituredesign.json",
    "gamedesign":"gamedesign.json",
    "graphicdesign":"graphicdesign.json",
    "informationdesign":"informationdesign.json",
    "inicet":"inicet.json",
    "interiordesigning":"interiordesigning.json",
    "jewellerydesign":"jewellerydesign.json",
    "knitweardesign":"knitweardesign.json",
    "leatherdesign":"leatherdesign.json",
    "mbbs":"mbbs.json",
    "md":"md.json",
    "mdes":"mdes.json",
    "medicine":"medicine.json",
    "mph":"mph.json",
    "mpt":"mpt.json",
    "neetmds":"neetmds.json",
    "neetpg":"neetpg.json",
    "neetss":"neetss.json",
    "nnetug":"nnetug.json",
    "paramedicalcourses":"paramedicalcourses.json",
    "pharmacycourse":"pharmacycourse.json",
    "pharmancycollegedetails1_40":"pharmancycollegedetails1_40.json",
    "pharmancycollegedetails41_80":"pharmancycollegedetails41_80.json",
    "pharmancycollegedetails81_125":"pharmancycollegedetails81_125.json",
    "physiotherapy":"physiotherapy.json",
    "productdesign":"productdesign.json",
    "publichealthmanagement":"publichealthmanagement.json",
    "textiledesign":"textiledesign.json",
    "topengineeringcollegedetails1_40":"topengineeringcollegedetails1_40.json",

}

@router.get("/{scraper_name}")
def get_scraper_data(scraper_name: str):
    if scraper_name not in SCRAPER_MAP:
        return {"error": "Scraper data not found"}
    file_path = os.path.join(DATA_PATH, SCRAPER_MAP[scraper_name])
    with open(file_path) as f:
        return json.load(f)
